export const GET_TRANSFUSION = 'GET_TRANSFUSION';
export const GET_TRANSFUSIONS = 'GET_TRANSFUSIONS';
export const ADD_TRANSFUSION = 'ADD_TRANSFUSION';
export const UPDATE_TRANSFUSION = 'UPDATE_TRANSFUSION';
export const DELETE_TRANSFUSION = 'DELETE_TRANSFUSION';

