export const GET_HOSPITAL = 'GET_HOSPITAL';
export const GET_HOSPITALS = 'GET_HOSPITALS';
export const ADD_HOSPITAL = 'ADD_HOSPITAL';
export const UPDATE_HOSPITAL = 'UPDATE_HOSPITAL';
export const DELETE_HOSPITAL = 'DELETE_HOSPITAL';

