export const GET_SUBSCRIBER = 'GET_SUBSCRIBER';
export const GET_SUBSCRIBERS = 'GET_SUBSCRIBERS';
export const ADD_SUBSCRIBER = 'ADD_SUBSCRIBER';
export const UPDATE_SUBSCRIBER = 'UPDATE_SUBSCRIBER';
export const DELETE_SUBSCRIBER = 'DELETE_SUBSCRIBER';

